export const game = [
    [null,null,null,{value: "c", index: 1},{value: "o"},{value: "e"},{value: "f"},{value: "i"},{value: "c", static: true},{value: "i"},{value: "e"},{value: "n"},{value: "t"},{value: "e"},{value: "s"}, null,null,null,null,null],
    [null,null,null,null,{value: "q", index: 2},{value: "u"},{value: "a"},{value: "t"},{value: "r", static: true},{value: "o"},null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,{value: "u", index: 3, static: true},{value: "m"},{value: "a"},null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,{value: "z", index: 4, static: true},{value: "e"},{value: "r"},{value: "o"},null,null,null,null,null,null,null,null],
    [null,{value: "c", index: 5},{value: "o"},{value: "m"},{value: "p"},{value: "l"},{value: "e"},{value: "t"},{value: "a", static: true},null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,{value: "d", index: 8, static: true},{value: "e"},{value: "l"},{value: "t"},{value: "a"},null,null,null,null,null,null,null],
    [null,null,null,null,null,{value: "v", index: 9},{value: "a"},{value: "z"},{value: "i", static: true},{value: "o"},null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,{value: "c", index: 8},{value: "i"},{value: "n", static: true},{value: "c"},{value: "o"},null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,{value: "b", index: 9},{value: "h", static: true},{value: "a"},{value: "s"},{value: "k"},{value: "a"},{value: "r"},{value: "a"},null,null,null,null,null],
    [null,null,null,null,null,null,{value: "q", index: 10},{value: "u"},{value: "a", static: true},{value: "t"},{value: "r"},{value: "o"},null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,{value: "*", static: true},null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,{value: "d", index: 11, static: true},{value: "e"},{value: "z"},{value: "o"},{value: "i"},{value: "t"},{value: "o"},null,null,null,null,null],
    [null,null,null,null,null,null,{value: "q", index: 12},{value: "u"},{value: "a", static: true},{value: "t"},{value: "o"},{value: "r"},{value: "z"},{value: "e"},null,null,null,null,null,null],
    [null,null,null,null,null,null,null,null,{value: "*", static: true},null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,{value: "m", index: 13},{value: "e", static: true},{value: "m"},{value: "b"},{value: "r"},{value: "o"},{value: "s"},null,null,null,null,null,null],
    [null,null,null,null,null,null,null,{value: "e", index: 14},{value: "q", static: true},{value: "u"},{value: "i"},{value: "l"},{value: "í"},{value: "b"},{value: "r"},{value: "i"},{value: "o"},null,null,null],
    [null,null,null,null,{value: "n", index: 15},{value: "e"},{value: "n"},{value: "h"},{value: "u", static: true},{value: "m"},{value: "a"},null,null,null,null,null,null,null,null,null],
    [{value: "i", index: 16},{value: "n"},{value: "c"},{value: "ó"},{value: "g"},{value: "n"},{value: "i"},{value: "t"},{value: "a", static: true},null,null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,{value: "s", index: 17},{value: "o"},{value: "l"},{value: "u"},{value: "ç", static: true},{value: "ã"},{value: "o"},null,null,null,null,null,null,null,null,null],
    [null,null,null,null,{value: "f", index: 18},{value: "r"},{value: "a"},{value: "ç"},{value: "ã", static: true},{value: "o"},null,null,null,null,null,null,null,null,null,null],
    [null,null,null,null,null,null,null,{value: "d", index: 19},{value: "o", static: true},{value: "i"},{value: "s"},null,null,null,null,null,null,null,null,null],
]

export const questions = [
    "Em uma equação do 2º grau completa as letras a, b e c são chamadas de...",
    "Qual a solução da equação 2x-10=-2?",
    "Quando o discriminante Δ de uma equação do 2º grau for igual a zero, ela terá ... raiz real.",
    "Qual é o conjunto soluçlão da equação 2x²=0?",
    "Uma equação do 2º grau que apresenta todos os coeficientes (a, b e c) diferentes de zero é chamada de equação do 2º grau ...",
    "O nome da letra grega que representa o discriminante na fórmula de Bhaskara é ...",
    "Em uma equação do 2º grau, em que o discriminante é um número negativo, o conjunto solução será ...",
    "A equação do 2º grau x²-5x=0 tem duas raízes. Qual é o número mairo do que zero que representa uma das raízes dessa equação?",
    "Como se chama a fórmula que utilizamos para resolver uma equação do 2º grau?",
    "Qual é o número menor do que zero que representa uma das raízes da equação do 2º grau 2x²+2x-8=0?",
    "Qual é a solução da equação 3+x=21?",
    "Na equação do 2º grau x²+14-10x=0, qual o valor do coeficiente c?",
    "Como se chama os termos que vêm antes e depois da igualdade de uma equação?",
    "Podemos fazer uma analogia entre uma equação e o ... dos dois pratos de uma balança.",
    "Se o discriminante de uma equação do 2º grau for negativo, quantas raízes terá a equação?",
    "Qual a denominação do valor desconhecido x de uma equação?",
    "Os resultados de uma equação representam o seu conjunto ...",
    "Ao resolvermos a equação do 2º grau 3x²-4x+1=0 encontramos duas raízes, uma representa um número inteiro e a outra representa uma ...",
    "A solução da equação 2x-5=5x-11 é?"
]